version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: nextmove-app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./app/uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://neondb_owner:jY4cAGISlB0Q@ep-old-leaf-a5ccos42.us-east-2.aws.neon.tech/neondb?sslmode=require
      - PGDATABASE=neondb
      - PGHOST=ep-old-leaf-a5ccos42.us-east-2.aws.neon.tech
      - PGUSER=neondb_owner
      - PGPASSWORD=jY4cAGISlB0Q
      - SMTP_HOST=smtp.strato.de
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - SMTP_USER=info@nextmove-consulting.de
      - SMTP_PASS=Nextmove2024!
      - SMTP_FROM=NextMove Solution <info@nextmove-consulting.de>
      - VITE_FACEBOOK_APP_ID=601823888901474
      - SESSION_SECRET=your-secret-key
      - CLIENT_URL=http://localhost
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
