version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: nextmove-app
    restart: always
    ports:
      - "3000:5000"
    volumes:
      - ./app:/app
      - ./app/uploads:/app/uploads:delegated
      - ./app/client/public:/app/client/public:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - NODE_OPTIONS=--enable-source-maps
      # Database
      - DATABASE_URL=postgresql://neondb_owner:jY4cAGISlB0Q@ep-old-leaf-a5ccos42.us-east-2.aws.neon.tech/neondb?sslmode=require
      - PGDATABASE=neondb
      - PGHOST=ep-old-leaf-a5ccos42.us-east-2.aws.neon.tech
      - PGUSER=neondb_owner
      - PGPASSWORD=jY4cAGISlB0Q
      # SMTP
      - SMTP_HOST=smtp.strato.de
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - SMTP_USER=info@nextmove-consulting.de
      - SMTP_PASS=!NextMoveConsulting123!
      - SMTP_FROM=NextMove Solution <info@nextmove-consulting.de>
      # Facebook
      - VITE_FACEBOOK_APP_ID=601823888901474
      - FACEBOOK_CLIENT_TOKEN=your_client_token
      - FACEBOOK_APP_SECRET=your_app_secret
      # Session
      - SESSION_SECRET=your-secret-key
      # URLs
      - CLIENT_URL=http://localhost:3000
      - VITE_API_URL=http://localhost:3000
      - VITE_ASSETS_URL=http://localhost:3000
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/uploads:/usr/share/nginx/uploads:ro
      - ./app/client/public:/usr/share/nginx/public:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
